# This is a basic workflow to help you get started with Actions
name: Automerge
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: release-*.*
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout latest develop branch
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          ref: 'develop'
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: automerge-branch
    - name: Checkout new branch
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          ref: 'automerge-branch'
    - name: Pull release branch
      run: git pull origin release-2.110
    # If we do NOT have a version bump and we are running this workflow, that means that there was subsequent changes to release branch (maybe HF).
      # We need to create a pull request from release branch into develop.
      # SUPER IMPORTANT: DO NOT DELETE THIS BRANCH AFTER MERGING.
    - name: Create pull request for release branch changes
      uses: peter-evans/create-pull-request@v3
      with:
          commit-message: Requesting merge from automerge-branch into develop
          branch: automerge-branch
          delete-branch: false # IMPORTANT: DO NOT delete our release branch
          base: develop
          title: '[Automated] Release Changes Into Develop'
          body: |
            # Automated Release Pull Request
            - Merging changes from `automerge-branch` into `develop`
            - Auto-generated by Automerge Github Action
          labels: |
            automated
            peer review
          draft: false
