name: Automerge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: release-*.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automerge:
    # Steps represent a sequence of tasks that will be executed as part of the job
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout latest develop branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: develop

    # Create a branch off of develop
    - name: Create Branch from develop
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: automerge-${{ steps.generate-uuid.outputs.uuid }}
        
    - name: perform
      run: |
        git checkout automerge-${{ steps.generate-uuid.outputs.uuid }}
        git pull origin release-2.110
        git push --set-upstream origin automerge-${{ steps.generate-uuid.outputs.uuid }}
        #if  there's a conflict we will fail
    
    # Create a PR for this merge
    - name: Create pull request for release branch changes
      uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
        release: automerge-${{ steps.generate-uuid.outputs.uuid }}
        dev: unused-do-not-change
        master: develop
        label: automated
        auto-merge: false # Important! the default will automerge, we don't want this
        require-merge: false
