name: Automerge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: release-*.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automerge:
    # Steps represent a sequence of tasks that will be executed as part of the job
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout latest master branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: 'master'
          
    # Create a branch off of develop
    - name: Create Branch from master
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'automerge-release-2.109'
      
    - name: Merge release to this branch of master
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        from_branch: 'release-2.109'
        target_branch: 'automerge-release-2.109'
      
      # Create a PR for this merge
    - name: Create pull request for release 2.109 -> master merge
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Merge of release-2.109 into master
        branch: 'automerge-release-2.109'
        delete-branch: true
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        title: '[Automated] Merge release -> develop'
        body: |
            # Automated Merge Release -> Develop
            - Merging release to develop
            - Auto-generated by Automerge Github Action

        labels: |
            automated
            peer review
        reviewers: seeegs
        draft: false
