# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'The tag to be build.'     
        required: true
    
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Determine Tag to Use
      run: | 
        if [ -z "${{ github.event.inputs.TAG }}" ]
        then
          echo "::set-env name=TAG_VALUE::${GITHUB_REF##*/}"
        else
          echo "::set-env name=TAG_VALUE::${{ github.event.inputs.TAG }}"
        fi
     
    # Runs a single command using the runners shell
    - name: Print right Tag
      run: echo $TAG_VALUE

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
